import { listChanges, getChangeStats } from "@mandujs/core";
import { getRootDir } from "../../util/fs";

export async function changeList(): Promise<boolean> {
  const rootDir = getRootDir();

  console.log(`🥟 Mandu Change List\n`);

  try {
    const changes = await listChanges(rootDir);
    const stats = await getChangeStats(rootDir);

    if (changes.length === 0) {
      console.log(`📭 변경 이력이 없습니다`);
      console.log(`\n💡 새 트랜잭션 시작: bunx mandu change begin`);
      return true;
    }

    // 통계
    console.log(`📊 통계:`);
    console.log(`   총 기록: ${stats.total}개`);
    console.log(`   활성: ${stats.active}개 | 확정: ${stats.committed}개 | 롤백: ${stats.rolledBack}개`);
    console.log(`   스냅샷: ${stats.snapshotCount}개\n`);

    // 최근 기록 (최신 순)
    console.log(`📜 변경 이력:`);

    const sortedChanges = [...changes].reverse(); // 최신 순

    for (const change of sortedChanges) {
      const statusIcon =
        change.status === "active"
          ? "🔄"
          : change.status === "committed"
            ? "✅"
            : "↩️";

      const date = new Date(change.createdAt).toLocaleString();

      console.log(`   ${statusIcon} ${change.id}`);
      console.log(`      상태: ${change.status}`);
      console.log(`      시간: ${date}`);
      if (change.message) {
        console.log(`      메시지: ${change.message}`);
      }
      if (change.autoGenerated) {
        console.log(`      생성: Auto-correct`);
      }
      console.log("");
    }

    return true;
  } catch (error) {
    console.error(`❌ 이력 조회 실패: ${error instanceof Error ? error.message : String(error)}`);
    return false;
  }
}
