import { getTransactionStatus } from "@mandujs/core";
import { getRootDir } from "../../util/fs";

export async function changeStatus(): Promise<boolean> {
  const rootDir = getRootDir();

  console.log(`🥟 Mandu Change Status\n`);

  try {
    const { state, change } = await getTransactionStatus(rootDir);

    if (state.active && change) {
      console.log(`🔄 활성 트랜잭션:`);
      console.log(`   ID: ${change.id}`);
      console.log(`   스냅샷: ${change.snapshotId}`);
      console.log(`   시작: ${new Date(change.createdAt).toLocaleString()}`);
      if (change.message) {
        console.log(`   메시지: ${change.message}`);
      }
      if (change.autoGenerated) {
        console.log(`   생성: Auto-correct`);
      }
      console.log(`\n💡 사용 가능한 명령:`);
      console.log(`   확정: bunx mandu change commit`);
      console.log(`   롤백: bunx mandu change rollback`);
    } else {
      console.log(`✅ 활성 트랜잭션 없음`);
      console.log(`\n💡 새 트랜잭션 시작: bunx mandu change begin`);
    }

    return true;
  } catch (error) {
    console.error(`❌ 상태 조회 실패: ${error instanceof Error ? error.message : String(error)}`);
    return false;
  }
}
