import type { RouteSpec } from "../spec/schema";

export function generateApiHandler(route: RouteSpec): string {
  return `// Generated by Mandu - DO NOT EDIT DIRECTLY
// Route ID: ${route.id}
// Pattern: ${route.pattern}

import type { Request } from "bun";

export default function handler(req: Request, params: Record<string, string>): Response {
  return Response.json({
    status: "ok",
    routeId: "${route.id}",
    pattern: "${route.pattern}",
    timestamp: new Date().toISOString(),
  });
}
`;
}

export function generatePageComponent(route: RouteSpec): string {
  const pageName = capitalize(route.id);
  return `// Generated by Mandu - DO NOT EDIT DIRECTLY
// Route ID: ${route.id}
// Pattern: ${route.pattern}

import React from "react";

interface Props {
  params: Record<string, string>;
}

export default function ${pageName}Page({ params }: Props): React.ReactElement {
  return React.createElement("div", null,
    React.createElement("h1", null, "${pageName} Page"),
    React.createElement("p", null, "Route ID: ${route.id}"),
    React.createElement("p", null, "Pattern: ${route.pattern}")
  );
}
`;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
