import type { RouteSpec } from "../spec/schema";

export function generateApiHandler(route: RouteSpec): string {
  // slotModule이 있으면 slot을 호출하는 버전 생성
  if (route.slotModule) {
    return generateApiHandlerWithSlot(route);
  }

  return `// Generated by Mandu - DO NOT EDIT DIRECTLY
// Route ID: ${route.id}
// Pattern: ${route.pattern}

import type { Request } from "bun";

export default function handler(req: Request, params: Record<string, string>): Response {
  return Response.json({
    status: "ok",
    routeId: "${route.id}",
    pattern: "${route.pattern}",
    timestamp: new Date().toISOString(),
  });
}
`;
}

export function generateApiHandlerWithSlot(route: RouteSpec): string {
  const slotImportPath = computeSlotImportPath(route.slotModule!, "apps/server/generated/routes");

  return `// Generated by Mandu - DO NOT EDIT DIRECTLY
// Route ID: ${route.id}
// Pattern: ${route.pattern}
// Slot Module: ${route.slotModule}

import type { Request } from "bun";
import filling from "${slotImportPath}";

export default async function handler(
  req: Request,
  params: Record<string, string>
): Promise<Response> {
  return filling.handle(req, params);
}
`;
}

export function generateSlotLogic(route: RouteSpec): string {
  return `// 🥟 Mandu Filling - ${route.id}
// Pattern: ${route.pattern}
// 이 파일에서 비즈니스 로직을 구현하세요.

import { Mandu } from "@mandujs/core";

export default Mandu.filling()
  // 📋 GET ${route.pattern}
  .get((ctx) => {
    return ctx.ok({
      message: "Hello from ${route.id}!",
      timestamp: new Date().toISOString(),
    });
  })

  // ➕ POST ${route.pattern}
  .post(async (ctx) => {
    const body = await ctx.body();
    return ctx.created({
      message: "Created!",
      received: body,
    });
  });

// 💡 사용 가능한 메서드:
// .get(ctx => ...)     - GET 요청 처리
// .post(ctx => ...)    - POST 요청 처리
// .put(ctx => ...)     - PUT 요청 처리
// .delete(ctx => ...)  - DELETE 요청 처리
// .guard(ctx => ...)   - 인증/검증 미들웨어
//
// 💡 Context (ctx) API:
// ctx.query            - Query parameters { name: 'value' }
// ctx.params           - Path parameters { id: '123' }
// ctx.body()           - Request body (자동 파싱)
// ctx.body(zodSchema)  - Body with validation
// ctx.headers          - Request headers
// ctx.ok(data)         - 200 OK
// ctx.created(data)    - 201 Created
// ctx.error(msg)       - 400 Bad Request
// ctx.notFound(msg)    - 404 Not Found
// ctx.set(key, value)  - Guard에서 Handler로 데이터 전달
// ctx.get(key)         - Guard에서 설정한 데이터 읽기
`;
}

function computeSlotImportPath(slotModule: string, fromDir: string): string {
  // slotModule: "apps/server/slots/users.logic.ts"
  // fromDir: "apps/server/generated/routes"
  // result: "../../slots/users.logic"

  const slotParts = slotModule.replace(/\\/g, "/").split("/");
  const fromParts = fromDir.replace(/\\/g, "/").split("/");

  // Find common prefix length
  let commonLength = 0;
  while (
    commonLength < slotParts.length &&
    commonLength < fromParts.length &&
    slotParts[commonLength] === fromParts[commonLength]
  ) {
    commonLength++;
  }

  // Calculate relative path
  const upCount = fromParts.length - commonLength;
  const relativeParts = slotParts.slice(commonLength);
  const ups = Array(upCount).fill("..");

  let result = [...ups, ...relativeParts].join("/");

  // Remove .ts extension
  result = result.replace(/\.ts$/, "");

  return result;
}

export function generatePageComponent(route: RouteSpec): string {
  const pageName = capitalize(route.id);
  return `// Generated by Mandu - DO NOT EDIT DIRECTLY
// Route ID: ${route.id}
// Pattern: ${route.pattern}

import React from "react";

interface Props {
  params: Record<string, string>;
}

export default function ${pageName}Page({ params }: Props): React.ReactElement {
  return React.createElement("div", null,
    React.createElement("h1", null, "${pageName} Page"),
    React.createElement("p", null, "Route ID: ${route.id}"),
    React.createElement("p", null, "Pattern: ${route.pattern}")
  );
}
`;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
