-- Generated by `mandu db plan` — edit with care
-- Version: 0001
-- Generated: 2026-04-18T04:51:29.926Z

CREATE TABLE "posts" (
  "id" TEXT PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "idx_posts_user_id" ON "posts" ("user_id");
