// AUTO-GENERATED by scripts/generate-official-skills.ts.
// Do not edit this file or sibling generated SKILL.md files.
export const OFFICIAL_SKILLS = [
  {
    "id": "mandu-agent-workflow",
    "description": "Canonical context -> plan -> apply -> verify -> repair workflow for Mandu agents"
  },
  {
    "id": "mandu-fs-routes",
    "description": "File-system page and API route authoring"
  },
  {
    "id": "mandu-contract",
    "description": "Typed API contract authoring and verification"
  },
  {
    "id": "mandu-hydration",
    "description": "Island and client-boundary hydration rules"
  },
  {
    "id": "mandu-guard",
    "description": "Architecture and generated-artifact safety rules"
  },
  {
    "id": "mandu-testing",
    "description": "Targeted Bun testing and verification workflow"
  }
] as const;
export const OFFICIAL_SKILL_IDS = [
  "mandu-agent-workflow",
  "mandu-fs-routes",
  "mandu-contract",
  "mandu-hydration",
  "mandu-guard",
  "mandu-testing"
] as const;
