#!/usr/bin/env bun

import fs from "fs/promises";
import path from "path";

interface SkillEntry {
  id: string;
  description: string;
}

interface SkillManifest {
  schemaVersion: number;
  skills: SkillEntry[];
}

const ROOT = path.resolve(import.meta.dir, "..");
const SOURCE_ROOT = path.join(ROOT, "skills", "official");
const TARGETS = [
  path.join(ROOT, "packages", "skills", "generated", "skills"),
  path.join(ROOT, "packages", "mcp", "src", "resources", "generated-skills"),
] as const;

export function renderOfficialSkillCatalog(manifest: SkillManifest): string {
  const ids = manifest.skills.map((skill) => skill.id);
  return [
    "// AUTO-GENERATED by scripts/generate-official-skills.ts.",
    "// Do not edit this file or sibling generated SKILL.md files.",
    `export const OFFICIAL_SKILLS = ${JSON.stringify(manifest.skills, null, 2)} as const;`,
    `export const OFFICIAL_SKILL_IDS = ${JSON.stringify(ids, null, 2)} as const;`,
    "",
  ].join("\n");
}

export async function generateOfficialSkills(): Promise<{ skills: number; files: number }> {
  const raw = await fs.readFile(path.join(SOURCE_ROOT, "manifest.json"), "utf8");
  const manifest = JSON.parse(raw) as SkillManifest;
  const ids = manifest.skills.map((skill) => skill.id);
  if (manifest.schemaVersion !== 1 || ids.length === 0 || new Set(ids).size !== ids.length) {
    throw new Error("Invalid official skill manifest");
  }

  const catalog = renderOfficialSkillCatalog(manifest);

  let files = 0;
  for (const target of TARGETS) {
    await fs.rm(target, { recursive: true, force: true });
    await fs.mkdir(target, { recursive: true });
    await fs.writeFile(path.join(target, "catalog.ts"), catalog, "utf8");
    files += 1;
    for (const id of ids) {
      const content = await fs.readFile(path.join(SOURCE_ROOT, id, "SKILL.md"), "utf8");
      const skillTarget = path.join(target, id);
      await fs.mkdir(skillTarget, { recursive: true });
      await fs.writeFile(path.join(skillTarget, "SKILL.md"), content, "utf8");
      files += 1;
    }
  }
  return { skills: ids.length, files };
}

if (import.meta.main) {
  const result = await generateOfficialSkills();
  console.log(`Generated ${result.skills} official skills into ${TARGETS.length} consumers (${result.files} files).`);
}
